name: UNESCAPE-JSON

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unescape-Json
    steps:
    - uses: actions/checkout@v2

    - name: unescape-Json
      id: unesc-json
      uses: ./

    # - name: unescape-Json
    #   run: echo -e "Result from unescape-Json:\n${{ steps.unescape-Json.outputs.result }}"
